In [1]:
# importing libries
import pandas as pd

In [2]:
tstV2_2019 = pd.read_excel('/Users/saadbin.mannan/Desktop/Task_1/Data/Transaction_Data.xlsx',sheet_name='tstV2-2019')
tstV2_2020 = pd.read_excel('/Users/saadbin.mannan/Desktop/Task_1/Data/Transaction_Data.xlsx',sheet_name='tstV2-2020')
Location_DB= pd.read_excel('/Users/saadbin.mannan/Desktop/Task_1/Data/Datalake.xlsx')

In [3]:
# Displaying location db data
Location_DB.tail(10)

      Bld_Name_En Estate_Name_En Phase_Name_En
22605        翡翠山莊            NaN           NaN
22606         聚庭軒            NaN           NaN
22607        荷泮雅苑            NaN           NaN
22608         華南居            NaN           NaN
22609        西沙豪園            NaN           NaN
22610          陶苑            NaN           NaN
22611        雅典花園            NaN           NaN
22612        雅麗豪園            NaN           NaN
22613        雍怡豪苑            NaN           NaN
22614         霸尾村            NaN           NaN

In [4]:
# Converting Data Frame into a list & For matching purpose converting all the string into lower case

building = [b.lower() for b in  Location_DB.Bld_Name_En]
# estate = [e.lower() for e in Location_DB.Estate_Name_En]
# phase = [p.lower() for p in Location_DB.Phase_Name_En]

# As we import data as dataframe it automatically fill all the values with NAN. 
# And we don't need these. So we are extracting estates and phase from dataframe

estate = []         
for i in range(0,1428):
    estate.append(Location_DB.Estate_Name_En[i])
estate = [e.lower() for e in estate]

phase = []
for i in range(0,458):
    phase.append(Location_DB.Phase_Name_En[i])
phase = [p.lower() for p in phase]

In [5]:
print(len(building))  #22615 buildings in Datalake
print(len(estate))      # 1428 estates in Datalake
print(len(phase))      # 458 phase in Datalake

22615
1428
458

#### 2019 transaction Data

In [6]:
check_19 = pd.DataFrame()
temp = pd.DataFrame()
b_cnt,e_cnt,p_cnt = 0,0,0
null_bld={}

for i in range(len(tstV2_2019)): #len(tstV2_2019)
    sub =tstV2_2019.location3[i].lower()
    count = tstV2_2019.Count[i]
    B_match = [i for i in building  if sub in i] 
    E_match = [i for i in estate  if sub in i]
    P_match = [i for i in phase  if sub in i]
    
    if len(B_match) == 0:
        B_match = 'NULL'
#      b_cnt = b_cnt+1
#      null_bld[sub] = count
#     print(sum(null_bld.values()))    # 7371 out of 17422 building id is null
    
    if len(E_match) ==0:
        E_match = 'NULL'
        e_cnt = e_cnt+1
    if  len(P_match) ==0:
        p_cnt = p_cnt+1
        P_match = 'NULL'
    temp = ({'TstV2_2019Bld':sub,'Building':B_match,'Estate':E_match,'Phase':P_match})
    check_19 = check_19.append(temp, ignore_index = True)

#### 2019 Sqft_wong Building Data Availability in Datalake

In [7]:
check_19.head(50)

,Building,Estate,Phase,TstV2_2019Bld
0,NULL,NULL,NULL,lai tsui court
1,"[hoi lok court block a, hoi lok court block b,...",[hoi lok court],NULL,hoi lok court
2,[grand central],NULL,NULL,grand central
3,"[choi hing court choi huen house (block a), ch...",NULL,NULL,choi hing court
4,"[18 upper east, upper east block 1a, upper eas...",[upper east],NULL,upper east
5,"[parc city, parc city tower 1, parc city tower...",[parc city],NULL,parc city
6,"[oasis kai tak - block 1, oasis kai tak - bloc...",[oasis kai tak],NULL,oasis kai tak
7,[emerald bay],NULL,NULL,emerald bay
8,"[eden manor - houses a1-c8, eden manor - tower...",[eden manor],NULL,eden manor
9,[upper riverbank],NULL,NULL,upper riverbank
10,"[caribbean coast - monterey cove tower 1, cari...","[monterey, monterey villas]","[caribbean coast phase 1 - monterey cove, roya...",monterey
11,"[st martin, st martin phase 1 tower 1, st mart...",[st martin],"[st martin phase 1, st martin phase 2]",st martin
12,[my central],NULL,NULL,my central
13,"[grand yoho phase 1 tower 1, grand yoho phase ...",[grand yoho],"[grand yoho phase 1, grand yoho phase 2]",grand yoho
14,NULL,NULL,NULL,one．artlane
15,[sol city],NULL,NULL,sol city
16,"[stanford residences victoria harbour, victori...",[victoria harbour - phase 1b],NULL,victoria harbour
17,[k.summit],NULL,NULL,k.summit
18,NULL,NULL,NULL,eltanin square mile
19,"[yoho town phase 2 - yoho midtown, yoho town p...",NULL,[yoho town phase 2 - yoho midtown],yoho midtown
20,NULL,NULL,NULL,banyan gdn
21,"[liberte block 1, liberte block 2, liberte blo...",[liberte],NULL,liberte
22,[the consonance],NULL,NULL,the consonance
23,"[l'aquatique, l'aquatique]",NULL,NULL,l'aquatique
24,"[metro town phase 2 - le point tower 10, metro...",[metro town],[metro town phase 2 - le point],metro town
25,"[metro town phase 2 - le point tower 10, metro...",NULL,[metro town phase 2 - le point],le point
26,"[alto residences, alto residences (houses), al...",[alto residences],NULL,alto residences
27,[park reach],NULL,NULL,park reach
28,"[marin point tower 1, marin point tower 2, mar...",[marin point],NULL,marin point
29,"[the parkside tower 1, the parkside tower 1a, ...",[the parkside],NULL,the parkside
30,[downtown 38],NULL,NULL,downtown 38
31,"[one homantin - tower 1, one homantin - tower ...",[one homantin],NULL,one homantin
32,NULL,NULL,NULL,residence譽88
33,NULL,NULL,NULL,79-85 hill road
34,"[one west kowloon, one west kowloon - tower 1,...",[one west kowloon],NULL,one west kowloon
35,NULL,NULL,NULL,"74-76 old main street, aberdeen"
36,"[lohas park phase 4a - wings at sea, lohas par...",NULL,"[lohas park phase 4a - wings at sea, lohas par...",wings at sea
37,"[the austin tower 1, the austin tower 1a, the ...",[the austin],NULL,the austin
38,"[wellesley, wellesley]",NULL,NULL,wellesley
39,NULL,NULL,NULL,72-94 wing kwong street
40,NULL,NULL,NULL,precinct two
41,NULL,NULL,NULL,mayfair by the sea i
42,[skypark],NULL,NULL,skypark
43,NULL,NULL,NULL,50-50a ngan hon street
44,"[the coronation tower 1, the coronation tower ...",[the coronation],NULL,the coronation
45,"[grand austin tower 1, grand austin tower 1a, ...",[grand austin],NULL,grand austin
46,[park ivy],NULL,NULL,park ivy
47,NULL,NULL,NULL,amber hse
48,NULL,NULL,NULL,54-54a ngan hon street
49,NULL,NULL,NULL,83 hill road

#### 2020 transaction Data

In [8]:
check_20 = pd.DataFrame()
temp = pd.DataFrame()
b_cnt,e_cnt,p_cnt = 0,0,0
null_bld={}

for i in range(len(tstV2_2020)): #len(tstV2_2019)
    sub =tstV2_2020.location3[i].lower()
    count = tstV2_2020.Count[i]
    B_match = [i for i in building  if sub in i] 
    E_match = [i for i in estate  if sub in i]
    P_match = [i for i in phase  if sub in i]
    
    if len(B_match) == 0:
        B_match = 'NULL'
#         b_cnt = b_cnt+1
#         null_bld[sub] = count
#     print(sum(null_bld.values()))    # 6947 out of 14340 building id is null
    
    if len(E_match) ==0:
        E_match = 'NULL'
        e_cnt = e_cnt+1
    if  len(P_match) ==0:
        p_cnt = p_cnt+1
        P_match = 'NULL'
    temp = ({'TstV2_2019Bld':sub,'Building':B_match,'Estate':E_match,'Phase':P_match})
    check_20 = check_20.append(temp, ignore_index = True)

#### 2020 Sqft_wong Building Data Availability in Datalake

In [9]:
check_20.head(50)

,Building,Estate,Phase,TstV2_2019Bld
0,"[wetland seasons park, wetland seasons park ph...",NULL,NULL,wetland seasons park
1,"[st martin, st martin phase 1 tower 1, st mart...",[st martin],"[st martin phase 1, st martin phase 2]",st martin
2,[emerald bay],NULL,NULL,emerald bay
3,NULL,NULL,NULL,kam fai court
4,NULL,NULL,NULL,kwun tak court
5,NULL,NULL,NULL,yuk wo court
6,[sol city],NULL,NULL,sol city
7,NULL,NULL,NULL,seacoast royale
8,NULL,NULL,NULL,sheung man court
9,[k.summit],NULL,NULL,k.summit
10,[oma by the sea],NULL,NULL,oma by the sea
11,[the campton],NULL,NULL,the campton
12,"[coo residence, coo residence]",NULL,NULL,coo residence
13,[downtown 38],NULL,NULL,downtown 38
14,"[grand yoho phase 1 tower 1, grand yoho phase ...",[grand yoho],"[grand yoho phase 1, grand yoho phase 2]",grand yoho
15,NULL,NULL,NULL,yung ming court
16,NULL,NULL,NULL,amber hse
17,"[18 upper east, upper east block 1a, upper eas...",[upper east],NULL,upper east
18,NULL,NULL,NULL,hoi tak court
19,[upper riverbank],NULL,NULL,upper riverbank
20,"[yoho town phase 2 - yoho midtown, yoho town p...",NULL,[yoho town phase 2 - yoho midtown],yoho midtown
21,[wing tak building - west wing],NULL,NULL,west wing
22,"[metro town phase 2 - le point tower 10, metro...",NULL,[metro town phase 2 - le point],le point
23,NULL,NULL,NULL,banyan gdn
24,"[liberte block 1, liberte block 2, liberte blo...",[liberte],NULL,liberte
25,NULL,NULL,NULL,emerald hse
26,"[metro town phase 2 - le point tower 10, metro...",[metro town],[metro town phase 2 - le point],metro town
27,NULL,NULL,NULL,one．artlane
28,NULL,NULL,NULL,wealthy gdn
29,[the richmond],NULL,NULL,the richmond
30,[cullinan west iii],NULL,NULL,cullinan west iii
31,"[lohas park phase 5a - malibu, lohas park phas...",NULL,[lohas park phase 5a - malibu],malibu
32,NULL,NULL,NULL,two．artlane
33,"[west park, west park]",NULL,NULL,west park
34,"[caribbean coast - monterey cove tower 1, cari...","[monterey, monterey villas]","[caribbean coast phase 1 - monterey cove, roya...",monterey
35,"[centra horizon, centra horizon]",NULL,NULL,centra horizon
36,"[the coronation tower 1, the coronation tower ...",[the coronation],NULL,the coronation
37,NULL,NULL,NULL,eltanin square mile
38,[skypark],NULL,NULL,skypark
39,[the consonance],NULL,NULL,the consonance
40,"[mount verdant, mount verdant]",NULL,NULL,mount verdant
41,"[alto residences, alto residences (houses), al...",[alto residences],NULL,alto residences
42,"[the met. bliss - block 1, the met. bliss - bl...",[the met. bliss],NULL,the met. bliss
43,[one eighty],NULL,NULL,one eighty
44,"[marin point tower 1, marin point tower 2, mar...",[marin point],NULL,marin point
45,[15 western street],NULL,NULL,15 western street
46,NULL,NULL,NULL,the shunning court
47,"[parc city, parc city tower 1, parc city tower...",[parc city],NULL,parc city
48,"[the parkside tower 1, the parkside tower 1a, ...",[the parkside],NULL,the parkside
49,"[eden manor - houses a1-c8, eden manor - tower...",[eden manor],NULL,eden manor